# Generated by Django 4.0.6 on 2024-12-26 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('idhabito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_habito', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('meta_diaria', models.IntegerField(help_text='Cantidad diaria objetivo (e.g., horas, minutos)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('idprogreso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tiempo_realizado', models.PositiveIntegerField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('idhabito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='Estudio.habito')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha_programada', models.DateTimeField()),
                ('frecuencia', models.CharField(choices=[('Diaria', 'Diaria'), ('Semanal', 'Semanal')], max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('idhabito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='Estudio.habito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='Estudio.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_limite', models.DateField()),
                ('idhabito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='Estudio.habito')),
            ],
        ),
        migrations.AddField(
            model_name='habito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='Estudio.usuario'),
        ),
    ]
